Task7/Writer/WriterApp/src/WriterApp.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WriterApp.Data.Model;
using WriterApp.Repository;
using WriterApp.Web.ViewModel;

namespace BookApp.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IWriterRepository _writerRepository;
        public BookController(
           IBookRepository bookRepository,
           IWriterRepository writerRepository
        )
        {
            _bookRepository = bookRepository;
            _writerRepository = writerRepository;
        }
        public IQueryable<Book> ApplyFilter(IQueryable<Book> query, string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
                return query.Where(s => s.Caption.ToUpper().Contains(searchString.ToUpper()) || s.Caption.ToUpper().Contains(searchString.ToUpper()));
            else
                return query;
        }
        public IQueryable<Book> ApplySortOrder(IQueryable<Book> query, string sortOrder, string direction)
        {
            switch (sortOrder)
            {
                case "caption":
                    query = direction == "ASC" ? query.OrderBy(s => s.Caption) : query.OrderByDescending(s => s.Caption);
                    break;
                case "date":
                    query = direction == "ASC" ? query.OrderBy(s => s.PublishedDate) : query.OrderByDescending(s => s.PublishedDate);
                    break;
                default:
                    query = direction == "ASC" ? query.OrderBy(s => s.Caption) : query.OrderByDescending(s => s.Caption);
                    break;
            }
            return query;
        }
        public async Task<IActionResult> Index(string sortOrder, string direction, string searchString, string currentFilter, int? page)
        {
            BookListViewModel bookList = new BookListViewModel();
            bookList.Filter = searchString;
            bookList.Order.Column = sortOrder;
            bookList.Order.Direction = direction ?? "ASC";
            bookList.Page = page ?? 1;
            if (bookList.Filter != null)
                bookList.Page = 1;
            else
                bookList.Filter = currentFilter;
            var books = _bookRepository.GetPage(bookList.Page, bookList.PageSize, (query) => ApplySortOrder(ApplyFilter(query, searchString), bookList.Order.Column, bookList.Order.Direction));
            bookList.Items = books.Select(x => new BookGridModel
            {
                Id = x.Id,
                Caption = x.Caption,
                PublishedDate = x.PublishedDate,
                Writers = x.WriterBooks.Select(w => new WriterGridModel { FullName = $"{w.Writer.LastName} {w.Writer.FirstName}", Id = w.Writer.Id }).ToList()
            }).ToList();
            bookList.TotalPages = (int)Math.Ceiling(books.TotalCount / (double)bookList.PageSize);
            return View(bookList);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            BookCreateModel book = new BookCreateModel();
            foreach (var w in _writerRepository.Get())
            {
                book.Writers.Add(new SelectListItem { Value = w.Id.ToString(), Text = $"{w.LastName} {w.FirstName}" });
            }
            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]                                       
        public async Task<IActionResult> Create(BookCreateModel model)
        {
            if (ModelState.IsValid)
            {
                Book book = new Book
                {
                    Caption = model.Caption,
                    PublishedDate = model.PublishedDate,
                    WriterBooks = new List<WriterBook>()
                };
                foreach (var id in model.WriterIds)
                {
                    book.WriterBooks.Add(new WriterBook { WriterId = id });
                }
                _bookRepository.Add(book);
                return RedirectToAction("Index");
            }
            foreach (var w in _writerRepository.Get())
            {
                model.Writers.Add(new SelectListItem { Value = w.Id.ToString(), Text = $"{w.LastName} {w.FirstName}" });
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Book book = _bookRepository.GetById(id);
            return View(new BookEditModel
            {
                Caption = book.Caption,
                PublishedDate = book.PublishedDate,
                WriterIds = book.WriterBooks.Select(x => x.WriterId).ToList(),
                Writers = _writerRepository.Get().Select(x => new SelectListItem { Value = x.Id.ToString(), Text = $"{x.LastName} {x.FirstName}" }).ToList()
            });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookEditModel model)
        {
            if (ModelState.IsValid)
            {
                Book book = new Book
                {
                    Id = id,
                    Caption = model.Caption,
                    PublishedDate = model.PublishedDate,
                    WriterBooks = new List<WriterBook>()
                };
                foreach (var wid in model.WriterIds)
                {
                    book.WriterBooks.Add(new WriterBook { WriterId = wid, BookId = id });
                }
                _bookRepository.Edit(book);
                return RedirectToAction("Index");
            }
            foreach (var w in _writerRepository.Get())
            {
                model.Writers.Add(new SelectListItem { Value = w.Id.ToString(), Text = $"{w.LastName} {w.FirstName}" });
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            _bookRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Task7/Writer/WriterApp/src/WriterApp.Web/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using WriterApp.Data.Model;
using WriterApp.Repository;
using WriterApp.Web.ViewModel;


namespace WriterApp.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly IWriterRepository _writerRepository;
        public ReportController(
           IWriterRepository writerRepository
        )
        {
            _writerRepository = writerRepository;
        }
        public IQueryable<WriterReport> ApplyFilter(IQueryable<WriterReport> query, string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
                return query.Where(s => s.FullName.ToUpper().Contains(searchString.ToUpper()));
            else
                return query;
        }
        public IQueryable<WriterReport> ApplySortOrder(IQueryable<WriterReport> query, string sortOrder, string direction)
        {
            switch (sortOrder)
            {
                case "fullname":
                    query = direction == "ASC" ? query.OrderBy(s => s.FullName) : query.OrderByDescending(s => s.FullName);
                    break;
                case "numberOfBooks":
                    query = direction == "ASC" ? query.OrderBy(s => s.NumberOfBooks) : query.OrderByDescending(s => s.NumberOfBooks);
                    break;
                default:
                    query = direction == "ASC" ? query.OrderBy(s => s.FullName) : query.OrderByDescending(s => s.FullName);
                    break;
            }
            return query;
        }
        public async Task<IActionResult> Index(string sortOrder, string direction, string searchString, string currentFilter, int? page)
        {
            ReportListViewModel reportList = new ReportListViewModel();
            reportList.Filter = searchString;
            reportList.Order.Column = sortOrder;
            reportList.Order.Direction = direction ?? "ASC";
            reportList.Page = page ?? 1;
            if (reportList.Filter != null)
                reportList.Page = 1;
            else
                reportList.Filter = currentFilter;
            var writers = _writerRepository.GetReportsPage(reportList.Page, reportList.PageSize, (query) => ApplySortOrder(ApplyFilter(query, searchString), reportList.Order.Column, reportList.Order.Direction));
            reportList.Items = writers.Select(x => new ReportGridModel
            {
                FullName = x.FullName,
                NumberOfBooks = x.NumberOfBooks,
                FirstBook = x.FirstBook,
                LastBook = x.LastBook
            }).ToList();
            reportList.TotalPages = (int)Math.Ceiling(writers.TotalCount / (double)reportList.PageSize);
            return View(reportList);
        }

    }
}

Task7/Writer/WriterApp/src/WriterApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WriterApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/choosen/chosen.min.css" />

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WriterApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Book" asp-action="Index">Books</a></li>
                    <li><a asp-area="" asp-controller="Report" asp-action="Index">Reports</a></li>
                    <li><a asp-area="" asp-controller="spa" asp-action="Index">SPA</a></li>


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - WriterApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/choosen/chosen.jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>